import matplotlib

matplotlib.use("Agg")

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
    PageBreak,
    Frame,
    PageTemplate
)

from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.pdfgen import canvas


DB_PATH = "database/db.sqlite3"


def generate_report_data():

    conn = sqlite3.connect(DB_PATH)


    df = pd.read_sql_query(
        """
        SELECT bin_id, fill_level, timestamp
        FROM bins
        ORDER BY timestamp
        """,
        conn
    )


    conn.close()



    # -------------------------
    # ANALYTICS
    # -------------------------


    total_records = len(df)


    average_fill = round(
        df["fill_level"].mean(),
        1
    )


    critical_records = len(
        df[df["fill_level"] >= 80]
    )


    highest_fill = df["fill_level"].max()


    highest_bin = df.loc[
        df["fill_level"].idxmax(),
        "bin_id"
    ]


    low_risk = len(
        df[df["fill_level"] < 50]
    )


    medium_risk = len(
        df[
            (df["fill_level"] >= 50)
            &
            (df["fill_level"] < 80)
        ]
    )


    high_risk = len(
        df[df["fill_level"] >= 80]
    )


    # -------------------------
    # HISTORICAL GRAPH
    # -------------------------


    trend_path = "reports/historical_trend.png"


    plt.figure(figsize=(9,4))


    plt.plot(
        df["timestamp"],
        df["fill_level"],
        linewidth=3
    )


    plt.title(
        "Historical Waste Fill Level Trend"
    )


    plt.xlabel("Time")

    plt.ylabel(
        "Fill Level (%)"
    )


    plt.xticks(rotation=45)

    plt.grid(alpha=0.3)

    plt.tight_layout()


    plt.savefig(
        trend_path,
        dpi=300
    )


    plt.close()



    # -------------------------
    # RISK CHART
    # -------------------------


    risk_path = "reports/risk_distribution.png"


    plt.figure(figsize=(6,4))


    plt.bar(

        ["Low","Medium","High"],

        [
            low_risk,
            medium_risk,
            high_risk
        ]

    )


    plt.title(
        "Waste Bin Risk Distribution"
    )


    plt.xlabel(
        "Risk Level"
    )


    plt.ylabel(
        "Number of Records"
    )


    plt.tight_layout()


    plt.savefig(
        risk_path,
        dpi=300
    )


    plt.close()



    return {


        "generated_time":
        datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        ),


        "total_records":
        total_records,


        "average_fill":
        average_fill,


        "critical_records":
        critical_records,


        "highest_bin":
        highest_bin,


        "highest_fill":
        highest_fill,


        "trend_path":
        trend_path,


        "risk_path":
        risk_path

    }



def add_page_decorations(canvas, doc):

    width, height = letter

    canvas.saveState()

    # BORDER
    canvas.setStrokeColor(colors.HexColor("#1d2b45"))
    canvas.setLineWidth(1)
    canvas.rect(20, 20, width - 40, height - 40)

    # HEADER BAR
    canvas.setFillColor(colors.HexColor("#1d2b45"))
    canvas.rect(20, height - 60, width - 40, 40, fill=1)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(40, height - 45, "SMART WASTE ANALYTICS REPORT")

    # FOOTER TEXT
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)
    canvas.drawString(40, 25, "Generated by Smart Waste Monitoring System")

    # PAGE NUMBER
    canvas.drawRightString(width - 40, 25, f"Page {doc.page}")

    canvas.restoreState()

def create_pdf_report():


    data = generate_report_data()


    pdf_path = (
        "reports/"
        "Smart_Waste_Analytics_Report.pdf"
    )


    document = SimpleDocTemplate(
    pdf_path,
    pagesize=letter,
    rightMargin=40,
    leftMargin=40,
    topMargin=80,
    bottomMargin=60
)
    frame = Frame(
    40,
    60,
    letter[0] - 80,
    letter[1] - 120,
    id="normal"
)

    document.addPageTemplates([
    PageTemplate(
        id="ReportTemplate",
        frames=[frame],
        onPage=add_page_decorations
    )
])


    styles = getSampleStyleSheet()


    content = []



    # TITLE


    content.append(

        Paragraph(

            "<font size=24><b>Smart Waste Monitoring System</b></font>",

            styles["Title"]
        )
    )

    content.append(
        Spacer(1,8)
    )

    content.append(

        Paragraph(

        "<font size=16>Analytics & Performance Report</font>",

        styles["Heading2"]

        )
    )


    content.append(
        Spacer(1,20)
    )



    content.append(

    Paragraph(

        f"<b>Report Generated:</b> {data['generated_time']}",

        styles["Normal"]

    )

)

    content.append(

    Paragraph(

        "<b>Generated By:</b> Smart Waste Monitoring System",

        styles["Normal"]

    )

)



    content.append(
        Spacer(1,20)
    )



    # SYSTEM OVERVIEW


    content.append(
    Paragraph(
        "<b>System Overview</b>",
        ParagraphStyle(
            name="CustomHeading",
            fontSize=14,
            textColor=colors.HexColor("#1d2b45"),
            spaceAfter=10
        )
    )
)


    content.append(

        Paragraph(

            """
            This report presents analytics generated
            from the smart waste monitoring system.
            The system analyses bin fill levels and
            identifies collection priorities.
            """,

            styles["Normal"]

        )

    )


    content.append(
        Spacer(1,20)
    )



    # SUMMARY TABLE


    table_data = [


        [
            "Metric",
            "Value"
        ],


        [
            "Total Records Analysed",
            data["total_records"]
        ],


        [
            "Average Fill Level",
            f"{data['average_fill']}%"
        ],


        [
            "Critical Records",
            data["critical_records"]
        ],


        [
            "Highest Risk Bin",
            data["highest_bin"]
        ],


        [
            "Highest Fill Level",
            f"{data['highest_fill']}%"
        ]


    ]



    table = Table(table_data)


    table.setStyle(

    TableStyle(

        [

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

            ("BOTTOMPADDING",(0,0),(-1,0),10),

            ("TOPPADDING",(0,0),(-1,0),10),

            ("ALIGN",(0,0),(-1,-1),"CENTER")

        ]

    )

)

    content.append(table)



    content.append(
        Spacer(1,25)
    )


    content.append(PageBreak())



    # TREND GRAPH


    content.append(

        Paragraph(
            "Historical Trend Analysis",
            styles["Heading2"]
        )

    )


    content.append(

        Image(
            data["trend_path"],
            width=470,
            height=230
        )

    )


    content.append(

    Paragraph(

        "Figure 1. Historical waste fill level trend across recorded sensor readings.",

        styles["Normal"]

    )

)

    content.append(
    Spacer(1,15)
)


    content.append(
        Spacer(1,20)
    )



    # RISK GRAPH


    content.append(

        Paragraph(
            "Risk Distribution Analysis",
            styles["Heading2"]
        )

    )


    content.append(

        Image(
            data["risk_path"],
            width=420,
            height=260
        )

    )


    content.append(

    Paragraph(

        "Figure 2. Distribution of low, medium and high risk waste records.",

        styles["Normal"]

    )

)

    content.append(
    Spacer(1,15)
)


    content.append(
        Spacer(1,20)
    )



    # CONCLUSION


    content.append(
    Table(
        [[
            Paragraph(
                """
                <b>System Assessment</b><br/><br/>
                The analytics module successfully evaluates historical waste
                accumulation trends and identifies high-priority collection
                requirements. The generated visualisations support operational
                decision-making by highlighting waste patterns and risk
                distribution across monitored bins.
                """,
                styles["Normal"]
            )
        ]],
        style=TableStyle([
            ("BACKGROUND", (0,0), (-1,-1), colors.whitesmoke),
            ("BOX", (0,0), (-1,-1), 1, colors.HexColor("#1d2b45")),
            ("PADDING", (0,0), (-1,-1), 12)
        ])
    )
)



    document.build(content)



    return pdf_path





if __name__ == "__main__":

    pdf = create_pdf_report()

    print(
        "Generated:",
        pdf
    )
    